# Training Params
EPOCH: 200
BATCH: 16
VAL_INTERVAL: 5
SAVE_INTERVAL: 5
EARLY_STOP_PATIENCE: 0
CONTINUE_TRAIN: False

# Device Params
GPU:
  USE: 0
  MULTI: False
CPU: False
# Dataloader worker
NUM_WORKER: 4

# Training Options
CUDNN: True
AMP: False
MODEL_EMA: False
MODEL_EMA_DECAY: 0.99
USE_CLIP_GRAD: True
CLIP_GRAD_NORM: 10
COMPILE: False
COMPILE_BACKEND: "inductor"
ADJUST_LR: False

# Output
OUTPUT: ./result/
TAG: ""

USE_MLFLOW: True
EXPERIMENT_NAME: "pytorch-project-template"
