# Training Params
BATCH: 16
CONTINUE_TRAIN: False
SEED: 42
SAVE_INTERVAL: 5

ITER_TRAIN: False
# Epoch Based
EPOCH: 200
VAL_INTERVAL: 5
# Iteration Based
MAX_ITER: 160000
STEP_ITER: 16000

# Device Params
GPU:
  USE: 0
  MULTI: False
CPU: False
# Dataloader worker
NUM_WORKER: 4
USE_RAM_CACHE: False

# Training Options
CUDNN: True
AMP: False
AMP_INIT_SCALE: False
MODEL_EMA: False
MODEL_EMA_DECAY: 0.99
USE_CLIP_GRAD: True
CLIP_GRAD_NORM: 10
COMPILE: False
COMPILE_BACKEND: "inductor"
ADJUST_LR: False

# Output
OUTPUT: ./result/
TAG: ""

# MLflow
USE_MLFLOW: True
MLFLOW_IGNORE_DIRS: ["models"]
MLFLOW_EXPERIMENT_NAME: "pytorch-project-template"
