name: ChainedScheduler
scheduler: ChainedScheduler
args:
  schedulers:
    - name: LinearLR
      args:
        start_factor: 0.00066667
        end_factor: 1e-3
        total_iters: 1
    - name: MultiStepLR
      args:
        # 割合で指定，Epochで自動計算
        milestones: [0.66, 0.90]
        gamma: 0.1
