epoch_scheduler:
  name: CosineLRScheduler_timm
  scheduler: cosine_timm
  checkpoint: null
  args:
    min_lr: 1e-6
    warmup_epochs: 5
    warmup_lr: 1e-4
    cycle_decay: 0.1
    noise: [0.8, 0.9]
    # warmup終了時の学習率をlrと同じにする
    warmup_prefix: false
    cycle_limit: 1
iter_scheduler: null
