epoch_scheduler:
  name: ReduceLROnPlateau
  scheduler: ReduceLROnPlateau
  checkpoint: null
  args:
    # factor : 学習率の減衰率
    # patience : 何ステップ向上しなければlrを変更するか
    patience: 5
    cooldown: 5
    min_lr: 1e-6
    factor: 0.5
    threshold: 0.1
    mode: "min"
iter_scheduler: null
