NAME: dataset
TYPE: Dataset

TRANSFORMS:
  TRAIN:
    - name: Resizer
      args:
        img_scale: [224, 224]
    - name: NormalizeImage
      args: null
  VAL:
    - name: Resizer
      args:
        img_scale: [224, 224]
    - name: NormalizeImage
      args: null
  TEST:
    - name: Resizer
      args:
        img_scale: [224, 224]
    - name: NormalizeImage
      args: null
