name: dummy_dataset
dataset: DummyDataset # Class名

train_transforms:
  - name: DummyTransform
    args: null
  - name: ToTensor
    args: null
train_batch_transforms: []
val_transforms:
  - name: DummyTransform
    args: null
  - name: ToTensor
    args: null
test_transforms:
  - name: DummyTransform
    args: null
  - name: ToTensor
    args: null
