__BASE__:
  - config/__BASE__/config.yaml
  - config/__BASE__/OPTIMIZER/Momentum.yaml
  - config/__BASE__/LR_SCHEDULER/ReduceLROnPlateau.yaml
  - config/__BASE__/DATASET/dataset.yaml

# MODEL Param
MODEL:
  NAME: Model_Name
  MODEL: Model # Class名
  PRE_TRAINED: True
  PRE_TRAINED_WEIGHT: result/PreTrain/efficientdet-d0.pth
  # Load Weight Path
  WEIGHT: "./"
  SYNC_BN: False
  TIMM_SYNC_BN: False
  FIND_UNUSED_PARAMETERS: False
  LOSS: loss
