__BASE__:
  - config/__BASE__/config.yaml
  - config/__BASE__/OPTIMIZER/Momentum.yaml
  - config/__BASE__/LR_SCHEDULER/ReduceLROnPlateau.yaml
  - config/__BASE__/LOSS/loss.yaml

__DATASET__: config/__BASE__/DATASET/dataset.yaml

EPOCH: 12

# MODEL Param
MODEL:
  NAME: Model_Name
  MODEL: Model # Class名

  BACKBONE: resnet50
  BACKBONE_ARGS:
    out_indices: [1, 2, 3]
  IMAGENET_PRE_TRAINED: true
  IMAGENET_PRE_TRAINED_WEIGHT: ""
  USE_BACKBONE_FEATURES: [2, 3, 4]

  INPUT_SIZE: [224, 224]

  PRE_TRAINED: false
  PRE_TRAINED_WEIGHT: ""
  WEIGHT: ""
  SYNC_BN: false
  FIND_UNUSED_PARAMETERS: false
  FREEZE_BN: true
  TIMM_SYNC_BN: false
