site_name: PyTorch Project Template
site_description: A modular PyTorch project template with configuration management and registry system

nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - Configuration: architecture/configuration.md
    - Registry System: architecture/registry.md
  - API Reference:
    - Config: api/config.md
    - Models: api/models.md
    - Dataloaders: api/dataloaders.md
    - Optimizer: api/optimizer.md
    - Scheduler: api/scheduler.md
    - Transform: api/transform.md
    - Evaluator: api/evaluator.md
    - Utils: api/utils.md

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            show_category_heading: true
            merge_init_into_class: true
            docstring_section_style: table
            members_order: source
            show_submodules: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true

docs_dir: doc/docs
site_dir: doc/site

# Watch additional directories for changes
watch:
  - src/
  - README.md

# Development server settings
dev_addr: 127.0.0.1:8000
use_directory_urls: true