[project]
name = "pytorch-project-template"
version = "3.0.0"
description = ""
authors = [{ name = "Junya Morioka", email = "mjun@mjunya.com" }]
dependencies = [
    "torch==2.2.1+cu121",
    "torchvision==0.17.1+cu121",
    "timm>=0.9.16",
    "kornia>=0.7.2",
    "mlflow>=2.12.1",
    "torchmetrics>=1.0.3",
    "natsort>=8.4.0",
    "tabulate>=0.9.0",
    "tqdm>=4.64.1",
    "matplotlib>=3.8.4",
    "omegaconf>=2.3.0",
    "opencv-python>=4.9.0.80",
    "python-dotenv>=1.0.1",
    "torchinfo>=1.8.0",
    "pynvml>=11.5.0",
    "psutil>=5.9.8",
    "torch-cpp @ https://github.com/mjun0812/torch_cpp/raw/main/dist/torch_cpp-1.0.0+torch221cu121-cp311-cp311-linux_x86_64.whl",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ruff>=0.4.2",
]

[[tool.rye.sources]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/pytorch_project_template"]
