defaults:
  # 分ける場合は以下のように
  # - _self_
  - MODEL: model
  - DATASET: dataset
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/run/dir: ./result/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Training Params
EPOCH: 200
BATCH: 16
VAL_INTERVAL: 5
SAVE_INTERVAL: 5
EARLY_STOP_PATIENCE: 0
CONTINUE_TRAIN: False

OPTIMIZER: "AdamW"
LR_SCHEDULER: "CosineLRScheduler"
LR: 1e-3

# Device Params
GPU:
  USE: 0
  MULTI: False
CPU: False
# Dataloader worker
NUM_WORKER: 4

# Mixed Precision
AMP: False

# Output
OUTPUT: ./result/
TAG: ""

USE_CLEARML: False
USE_MLFLOW: True
EXPERIMENT_NAME: "pytorch-project-template"

hydra:
  output_subdir: null
  run:
    dir: .
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: train
    storage: null
    n_trials: 20
    n_jobs: 1

    search_space:
      DATASET.FRAME:
        type: int
        low: 5
        high: 60
        step: 5
