defaults:
  # 分ける場合は以下のように
  # - _self_
  # - MODEL: efficientdet-d0
  - override hydra/job_logging: disabled
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

# Training Params
EPOCH: 150
BATCH: 2
VAL_INTERVAL: 5
SAVE_INTERVAL: 5
EARLY_STOP_PATIENCE: 0
CONTINUE_TRAIN: False

OPTIMIZER: "AdamW"
LR_SCHEDULER: "sgdr"
LR: 1e-3

# Device Params
GPU:
  USE: 0
  MULTI: False
CPU: False
# Dataloader worker
NUM_WORKER: 4

# Mixed Precision
AMP: False

# Output
OUTPUT_PATH: ./result/
TAG: ""

# MODEL Param
MODEL:
  NAME: Model_Name
  MODEL: Model # Class名
  PRE_TRAINED: True
  PRE_TRAINED_WEIGHT: result/PreTrain/efficientdet-d0.pth
  LOSS: FocalLoss_EfficientDet
  GRAPH: False
  INPUT_SIZE: 512
  # Load Weight Path
  WEIGHT: "./"

# Dataset Info
DATASET:
  NAME: dataset_name
  TRAIN_LIST: ../dataset/coco128/annotations/annotations.csv
  VAL_LIST: ../dataset/coco128/annotations/annotations.csv
  TEST_LIST: ../dataset/coco128/annotations/annotations.csv
  CLASS_LIST: ../dataset/coco128/annotations/classes.csv
  NUM_CLASSES: 80
  TRANSFORMS:
    TRAIN:
      - name: RandomLRFlip
        args:
          width: 1.0
          num_point_feature: ${DATASET.NUM_POINT_FEATURE}
    VAL:
      - name: RandomLRFlip
        args:
          width: 1.0
          num_point_feature: ${DATASET.NUM_POINT_FEATURE}
    TEST:
      - name: TransformStGCN
        args:
          frame: ${DATASET.FRAME}
          point_num: 33

hydra:
  run:
    dir: ./result/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: train
    storage: null
    n_trials: 20
    n_jobs: 1

    search_space:
      DATASET.FRAME:
        type: int
        low: 5
        high: 60
        step: 5
